name: ai_nexconn_chat_plugin_example
description: A demo app for ai_nexconn_chat_plugin SDK.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  ai_nexconn_chat_plugin:
    path: ../
  rongcloud_im_wrapper_plugin: ^5.32.6
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  record: ^6.0.0
  path_provider: ^2.1.5
  just_audio: ^0.10.0
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
