/// A lookup table mapping numeric error codes to human-readable reason strings.
///
/// These error codes come from the server and the SDK. Use
/// [NCError.code] to look up the corresponding description.
const errorCodeReasons = <int, String>{
  -101: 'Invalid parameter',
  -4:
      'The application has not called connect(); call this method after the connection succeeds',
  -3: 'Failed to cancel pause',
  -2: 'The IPC process terminated unexpectedly',
  -1: 'Unknown error',
  405:
      'Message sending failed because you were added to the other party\'s blocklist',
  407:
      'Message sending failed because the recipient only accepts messages from the allowlist and you are not on it',
  1004: 'Authentication error',
  20109: 'System conversations do not support sending this message',
  20112: 'The message content contains sensitive words',
  20113: 'The message content did not pass moderation',
  20114: 'The message is beyond the editable time window',
  20115: 'The message size exceeds the limit',
  20116: 'This message does not support editing',
  20512:
      'The AppKey data center does not match the data center requested by cloud control',
  20604:
      'Message sending rate is too high; at most 5 messages can be sent per second',
  20605: 'Operation is forbidden; this error code has been deprecated',
  20606:
      'Operation is unsupported; server-side has disabled this operation and it is only available for private cloud',
  20607: 'The request exceeded the rate limit; try again later',
  21406: 'Not in the discussion group',
  21501:
      'The sent message contains sensitive words (sending fails and the receiver will not receive it)',
  21502:
      'Sensitive words in the message have been replaced (the receiver can receive the replaced message)',
  22201: 'The original message does not exist',
  22202:
      'This is an Ultra Group expansion message, but the original message does not support expansion',
  22203:
      'This is an Ultra Group expansion message, but the expansion content format is invalid',
  22204:
      'This is an Ultra Group expansion message, but you do not have permission to operate on it',
  22406: 'Not in this group',
  22408: 'Muted in this group',
  23406: 'Not in this chat room',
  23407:
      'The number of users in the chat room mute allowlist exceeds the limit',
  23408: 'Muted in this chat room',
  23409: 'You have been kicked out and banned from joining the chat room',
  23410: 'The chat room does not exist',
  23411: 'The number of chat room members exceeds the limit',
  23412: 'Invalid chat room API parameter',
  23414: 'Chat room cloud storage is not enabled',
  23423:
      'The number of chat room KV attributes exceeds the limit; the default maximum is 100 per chat room',
  23424:
      'You do not have permission to modify existing attribute values in the chat room',
  23425:
      'The chat room status update frequency exceeds the limit; at most 100 set/delete operations per second are allowed in one chat room',
  23426: 'Custom chat room attribute settings are not enabled',
  23427: 'The chat room attribute does not exist',
  23428: 'Batch setting or deleting chat room KV values partially failed',
  23429:
      'The number of chat room KV entries in a batch set/delete operation exceeds the limit (up to 10 at a time)',
  23431:
      'Failed to set chat room KV; this occurs when two users or multiple devices operate on the same KV at the same time',
  23437:
      'The join-chat-room extra info is too long; the default maximum length is 128 characters',
  24360:
      'You do not have permission to set this managed user profile attribute',
  24361:
      'This key is not in the key list of managed basic user profile attributes',
  24362:
      'This key is not in the key list of managed extended user profile attributes',
  24363:
      'The number of managed extended user profile attributes exceeds the maximum allowed',
  24364:
      'The value of the managed user profile attribute exceeds the maximum length',
  24365:
      'The number of managed user profiles in a batch query exceeds the limit of 100',
  24366: 'This user does not exist',
  24367: 'The value of this managed user profile attribute must be numeric',
  24368:
      'The value of this managed user profile attribute is out of the allowed range',
  24369: 'Managed user profile is not enabled',
  24401: 'Ultra Group is not enabled',
  24402: 'Ultra Group service exception',
  24403: 'Ultra Group parameter error',
  24404: 'Unknown Ultra Group exception',
  24406: 'Not an Ultra Group member',
  24408: 'Ultra Group member is muted',
  24410: 'Ultra Group does not exist',
  24411: 'The number of Ultra Group members exceeds the limit',
  24412: 'The number of Ultra Groups the user joined exceeds the limit',
  24413:
      'The number of Ultra Group channels exceeds the limit when creating a channel',
  24414: 'The Ultra Group channel ID does not exist',
  24415: 'Ultra Group channel message sending exceeds the limit',
  24416: 'The user is not in the private Ultra Group channel',
  25101: 'Invalid parameters for recalling a message',
  25102: 'Single/group chat cloud storage is not enabled',
  25104: 'Unknown exception',
  25107:
      'Recalling other people\'s messages is not allowed (server-side switch is enabled)',
  25402: 'Managed service exception',
  25403: 'Managed service parameter error',
  25404:
      'Illegal operation; only the group owner can modify group permission-related settings',
  25405: 'No permission to perform this operation',
  25406: 'Invalid parameter; length exceeds the limit',
  25407: 'Invalid parameter; illegal characters detected',
  25408: 'The parameter value must be numeric',
  25409: 'The group ID already exists',
  25410: 'The group ID does not exist',
  25411: 'The number of group members exceeds the limit',
  25412: 'The group member ID is already in the current group',
  25413: 'This operation is not allowed through the SDK',
  25414: 'No one is allowed to join, so the group cannot be joined',
  25415: 'The extension info key does not exist',
  25416: 'Query rate limit exceeded',
  25417: 'The group owner cannot be kicked out or leave the group',
  25418: 'The user ID is not in the group',
  25419: 'The number of administrators/followers exceeds the limit',
  25420: 'The user ID is not in the current group administrators',
  25421: 'There is no invitation request for the given group ID and user ID',
  25422: 'The number of queried groups exceeds the limit',
  25423: 'The group name cannot be empty',
  25424: 'Joining the group requires admin approval',
  25425: 'The group owner cannot be set as an administrator',
  25426: 'No permission to invite others into the group',
  25427: 'Inviting someone into the group requires the invitee\'s consent',
  25428:
      'Another administrator has already processed the request while the admin or group owner was handling it',
  25429:
      'Legacy groups do not support managed APIs and must be imported before use',
  25430: 'The group ID is invalid and contains special characters',
  25432: 'Failed to parse pageToken',
  25460: 'You are already friends; the operation is invalid',
  25461: 'You can add this user as a friend only after they agree',
  25462:
      'You cannot add this user as a friend because you are in the target user\'s blocklist',
  25463:
      'You cannot add this user as a friend because you are not in the target user\'s allowlist',
  25464:
      'You cannot add this user as a friend because the target user is in the current user\'s blocklist',
  25465:
      'You cannot add this user as a friend because you are not in the current user\'s allowlist',
  25466: 'Invalid operation; the friend request does not exist or has expired',
  25467: 'The current user\'s number of friends exceeds the limit',
  25468: 'The target user\'s number of friends exceeds the limit',
  25469: 'This operation cannot be performed because you are not friends',
  25470: 'Custom friend attributes exceed the limit',
  25471: 'The other party does not allow being added as a friend',
  25472: 'Friend does not exist',
  25473: 'You cannot add yourself as a friend',
  25474: 'Adding a bot as a friend is not supported',
  25480: 'The managed profile information did not pass moderation',
  26001: 'The user-level settings service request parameter is invalid',
  26002: 'The client version is too low and needs to be synced',
  26003: 'Internal service error',
  26004:
      'The number of user conversation tags exceeds the limit; at most 20 tags are supported',
  26005: 'V4 read receipt is not enabled',
  26006: 'Conversation driver is not enabled',
  26007: 'The message ID order is incorrect',
  26008: 'The reported time does not support synchronization',
  26009: 'The message ID is invalid',
  26010: 'Invalid parameter',
  26020: 'Online status subscription is not enabled',
  26021: 'The number of subscribers for the user has reached the limit',
  26022: 'The number of subscribed users has reached the limit',
  26101: 'Short video service is not enabled',
  26106: 'The uploaded file exceeds the maximum limit',
  26107: 'The size parameter is missing when the limit is enabled',
  26200: 'Translation succeeded',
  26201:
      'Translation failed because RongCloud authentication failed or the token expired',
  26202:
      'Translation failed because the translation provider authentication failed',
  26203:
      'Translation failed because the translation provider returned an error',
  26204:
      'Translation failed because the translation feature is not enabled in RongCloud',
  26206:
      'Translation failed because the server does not have the secret for the authentication token',
  26208: 'The short voice transcription result is empty; verify the codec type',
  26209: 'Invalid language setting',
  26210: 'Invalid encoding format setting',
  26314: 'V5 is not enabled',
  26315: 'Unsupported read receipt mode',
  26316: 'Parameter length exceeds the limit',
  26317: 'Unsupported conversation type',
  26318: 'Unsupported read query type',
  26320: 'Not the message sender',
  26321: 'The message type does not require a receipt',
  26322: 'Message does not exist',
  28300: 'Speech conversion service is not enabled',
  28304: 'STT conversion failed',
  28305: 'Speech-to-text service exception',
  28306: 'Missing parameters for speech-to-text',
  28307: 'Usage exceeds the limit',
  28400: 'Translation service is not enabled',
  28401: 'Translation failed',
  28402: 'Translation server error',
  28403: 'Missing required parameter',
  28404: 'Invalid parameter format',
  28405: 'Usage exceeds the quota',
  28406: 'Text length exceeds the limit',
  28407: 'Unsupported language',
  29002: 'The message stream does not exist',
  29003: 'The stream ended because no data was received for 30 seconds',
  29004: 'The stream was truncated after exceeding 30 minutes',
  29005: 'Moderation failed and the stream data was deleted',
  29006: 'The stream data exceeded 128 KB and was truncated',
  29007: 'Internal exception in the stream message service',
  29102: 'Official account is followed by default (APP_PUBLIC_SERVICE)',
  29103: 'Official account is already followed (APP_PUBLIC_SERVICE)',
  29104: 'Official account is unfollowed by default (APP_PUBLIC_SERVICE)',
  29105: 'Official account has already been unfollowed (APP_PUBLIC_SERVICE)',
  29106: 'This official account is not followed (APP_PUBLIC_SERVICE)',
  29201: 'Invalid official account (PUBLIC_SERVICE)',
  29202: 'Official account is followed by default (PUBLIC_SERVICE)',
  29203: 'Official account is already followed (PUBLIC_SERVICE)',
  29204: 'Official account is unfollowed by default (PUBLIC_SERVICE)',
  29205: 'Official account has already been unfollowed (PUBLIC_SERVICE)',
  29206: 'Official account is not followed (PUBLIC_SERVICE)',
  29301: 'Failed to request the large language model',
  29302: 'Large language model response error',
  29303: 'Large language model response timeout',
  29310: 'The agentId in the request does not exist',
  29311: 'Unsupported large language model provider',
  29320: 'Invalid request parameter format',
  29321: 'Invalid request parameter: channelType',
  29322: 'Invalid request parameter: channelId',
  29323: 'Invalid request parameter: targetId',
  29324: 'Invalid request parameter: message.userId',
  29325: 'Invalid request parameter: message.messageId',
  29326: 'Invalid request parameter: message.username',
  29327: 'Invalid request parameter: message.type',
  29328: 'Invalid request parameter: message.content',
  29329: 'Invalid request parameter: message.timestamp',
  29330: 'Invalid request parameter: agentId',
  29331: 'The number of keys in customInfo exceeds the limit',
  29332: 'The length of keys/values in customInfo exceeds the limit',
  29399: 'Unknown server error (HTTP 500)',
  30001: 'The current connection has already been released',
  30002: 'The current connection is unavailable',
  30003:
      'The server timed out while responding to the client message send request',
  30004: 'Navigation HTTP request failed',
  30005: 'Failed to request the navigation endpoint',
  30006: 'Navigation HTTP receive failed',
  30007: 'Invalid navigation response',
  30008: 'Invalid format of the navigation HTTP response data',
  30009: 'No valid IP address exists in the parsed navigation data',
  30010: 'Failed to create the connection',
  30011: 'Connection disconnected',
  30012: 'PING failed',
  30013: 'PING timed out',
  30014: 'Signaling send failed',
  30015: 'Connections are being made too frequently',
  30016:
      'The message size exceeds the limit; the message body can be at most 128 KB',
  30017: 'This message type is not supported for sending',
  30019: 'Network connection is unavailable',
  30021: 'TCP connection succeeded, but the RMTP connection failed',
  31000: 'Connection ACK timed out',
  31001: 'Invalid signaling version',
  31002: 'Invalid client info field format',
  31003: 'Connection service is not enabled',
  31004:
      'Token is invalid; AppKey and Token do not match; or Token has expired',
  31005: 'App verification failed',
  31006: 'Connection redirected',
  31007: 'The package name does not match the registration info in the backend',
  31008: 'The AppKey has been banned or deleted',
  31009: 'Connection failed because the user is banned',
  31010: 'The user was kicked offline',
  31011: 'The user is banned and the IM connection was passively disconnected',
  31012: 'Link encryption authentication failed',
  31020: 'Token has expired',
  31023:
      'A client of the same type is already online (the no-kick-off switch is enabled)',
  31024:
      'The total number of connections exceeds the service\'s concurrent connection limit (private cloud only)',
  31025:
      'The client connected to the wrong environment and the connection was rejected',
  31026: 'AppServer joint authentication failed',
  31027:
      'This token has already been used and cannot be used again to connect (one-time token)',
  31029: 'The user account has been deleted',
  31030: 'The private cloud license has expired',
  31031: 'Invalid request parameter: channelType',
  31032: 'Invalid agent prompt type',
  31033: 'Agent service is unavailable',
  31034: 'Invalid request parameter: message.userId',
  31035: 'Invalid request parameter: message.messageId',
  31036: 'Invalid request parameter: message.username',
  31037: 'Invalid request parameter: message.type',
  31038: 'Invalid request parameter: message.content',
  31039: 'Invalid request parameter: message.timestamp',
  31040: 'Invalid request parameter: agentId',
  31041: 'The recommendationParams type in the agent API is invalid',
  31042: 'The type of the context message list in the agent API is invalid',
  31043: 'The type of a context message in the agent API is invalid',
  31044: 'The number of context messages in the agent API exceeds the maximum',
  32001: 'Internal protocol layer error: invalid data',
  32002: 'Internal protocol layer error',
  32011:
      'The server actively disconnected the connection (only triggered under QUIC)',
  32054:
      'The connection was interrupted by the server; the SDK will automatically reconnect',
  32061: 'Connection rejected',
  33000: 'Failed to store the message in the local database',
  33001: 'The protocol stack is not initialized',
  33002: 'Database error',
  33003: 'Invalid parameters were passed when calling the API',
  33004: 'Invalid channel',
  33005: 'Reconnected successfully',
  33006: 'Connection in progress; calling connect again is rejected',
  33007: 'Cloud storage for historical messages is not enabled',
  33008: 'Failed to save the message to the local database',
  33009: 'The chat room has been recycled',
  33010:
      'Database encryption migration failed, possibly due to insufficient disk space',
  33011:
      'Database decryption migration failed, possibly due to insufficient disk space',
  33012:
      'Database deletion failed, possibly because the connection was not disconnected',
  33100: 'Tag does not exist',
  33101: 'Tag already exists',
  33102: 'Tag is not in the conversation',
  33401: 'The edited message was received or was not sent successfully',
  33402: 'The edited message is beyond the editable time limit',
  34001: 'Connection already exists',
  34002:
      'The short video duration exceeds the limit; the default maximum is 2 minutes',
  34003: 'The GIF message file size exceeds the limit',
  34004: 'Chat room state synchronization is not completed',
  34005: 'Incorrect connection environment',
  34006: 'Connection timed out',
  34007: 'The queried public service information does not exist',
  34008: 'The message cannot be expanded',
  34009: 'Message expansion failed, usually due to a network issue',
  34010: 'The message expansion size exceeds the limit',
  34011: 'Media message file upload failed',
  34012: 'The specified conversation type does not support tags',
  34013:
      'The number of conversations added to or removed from the tag exceeds the limit; up to 1000 are allowed',
  34014: 'This version does not support group read receipts',
  34015: 'Video compression failed',
  34016: 'User-level settings are not enabled',
  34017: 'The message returned by the message interceptor handler is empty',
  34018:
      'Media file upload exception; the file does not exist or its size is 0',
  34019: 'The uploaded media file format is not supported',
  34020: 'The file has expired or been cleaned up',
  34021: 'The message is not registered',
  34022: 'This API does not support Ultra Group conversations',
  34023: 'readReceiptUsersOption is null',
  34024: 'The Ultra Group channel does not exist',
  34025:
      'Message expansion failed because the conversation type does not match',
  34026:
      'HTTP request IO exception, possibly because the network is unavailable',
  34027: 'HTTP request timed out',
  34028: 'Redirection is not allowed for this request; use the actual file URL',
  34029: 'This message does not support read receipts',
  34030: 'Received HTTP 403 Forbidden while downloading the file',
  34100: 'authToken is not set or is empty',
  34101: 'The text to translate is empty',
  34102: 'The target language is empty',
  34103: 'The source language is empty',
  34104: 'The translation server URL is empty',
  34105: 'App Key is empty',
  34106: 'Invalid server data',
  34129: 'ConnectOption is null during connection',
  34131: 'Invalid version parameter used during connection',
  34200: 'The provided language is invalid',
  34201: 'The provided conversation type is not supported by the API',
  34202: 'The provided timestamp is invalid',
  34203: 'The provided uid (unique server message ID) is invalid',
  34204:
      'The provided messageId is invalid or the corresponding Message cannot be found',
  34205: 'The provided Message or MessageContent is invalid',
  34206: 'The provided messageList is invalid',
  34207: 'The provided mediaType is invalid',
  34208: 'The provided requestUrl is invalid',
  34209: 'The provided ConversationType is invalid',
  34210: 'The provided targetId is invalid',
  34211: 'The provided channelId is invalid',
  34212: 'The provided tagId is invalid',
  34213: 'The provided tagName is invalid',
  34214: 'The provided userId is invalid',
  34215: 'The provided userIdList is invalid',
  34218: 'Invalid parameter passed to setOfflineMessageDuration',
  34219: 'The provided HistoryMessageOption is invalid',
  34220: 'The provided MessageExpansion is invalid',
  34221: 'The provided keyArray for Ultra Group message expansion is invalid',
  34223: 'sendMediaMessage did not receive a media message',
  34224: 'The provided time string parameter is invalid',
  34225: 'The provided ConversationIdentifier is invalid',
  34228: 'Invalid PushNotificationLevel',
  34229: 'The provided messageIds is null or has a length of 0',
  34230: 'ReceivedStatus is null',
  34231: 'Invalid Ultra Group channel type',
  34232: 'The provided count is invalid',
  34233: 'The provided sendTime is invalid',
  34234: 'The provided local path does not exist',
  34235: 'The provided mediaUrl is empty',
  34236: 'The provided uniqueId is empty',
  34237: 'The provided MessageTag is empty',
  34238: 'Invalid proxy configuration',
  34239: 'Invalid proxy test service passed to testProxy',
  34240: 'The testProxy API is unreachable',
  34241: 'recallUltraGroupMessage recalled an unsupported message type',
  34242: 'The provided conversations is null',
  34243: 'The provided message is empty',
  34244: 'SentStatus is null',
  34245: 'The configured proxy address is unavailable',
  34246: 'Failed to update the message read status',
  34247: 'Failed to clear the message unread status',
  34248: 'Failed to set the message read timestamp',
  34249: 'Failed to get the remote push language',
  34250: 'Failed to get the offline message duration',
  34251: 'Failed to save the file',
  34252: 'The file does not exist',
  34253: 'Invalid file length',
  34254: 'Invalid download URL',
  34255: 'Invalid chunk index',
  34256: 'Invalid upload ID',
  34257: 'Invalid App Key',
  34258: 'Invalid JoinMode parameter',
  34259: 'Invalid rtcRoomID parameter',
  34260: 'Invalid key parameter',
  34261: 'Invalid keys parameter',
  34262: 'Invalid value parameter',
  34263: 'Invalid entries parameter',
  34264: 'Invalid notificationExtra parameter',
  34265: 'Invalid ChatRoomMemberOrder parameter',
  34266: 'Invalid TimestampOrder parameter',
  34267: 'Invalid MessageDirection parameter',
  34268: 'Invalid status parameter',
  34269: 'Invalid title parameter',
  34270: 'Invalid portrait parameter',
  34271: 'Invalid objectName parameter',
  34272: 'Invalid before parameter',
  34273: 'Invalid after parameter',
  34274: 'Invalid keyword parameter',
  34275: 'Invalid objectName list parameter',
  34276: 'Invalid offset parameter',
  34277: 'Invalid start time parameter',
  34278: 'Invalid end time parameter',
  34279: 'Invalid limit parameter',
  34280: 'Invalid MessageDirection',
  34281: 'Invalid SentStatus',
  34282: 'Invalid targetId list parameter',
  34283: 'Invalid span minutes parameter',
  34284: 'Invalid ConversationType list parameter',
  34285: 'Invalid message handler',
  34287: 'The provided ConversationIdentifier array is invalid',
  34288: 'The provided ClearMessageOption array is invalid',
  34289: 'Invalid startMessageUID parameter',
  34290: 'Invalid endMessageUID parameter',
  34291: 'V4 read receipt is not supported',
  34292: 'Updating V4 read receipt information is not supported',
  34296:
      'The provided conversation type is not supported when sending directional messages',
  34300: 'The multimedia upload/download interceptor returned a null conn',
  34301: 'Database is not initialized',
  34302: 'Database error',
  34303: 'Database SQL execution exception',
  34304: 'Queried data does not exist',
  34305: 'Failed to parse network data',
  34306: 'Invalid subscription type passed to the subscription event',
  34307:
      'Invalid subscription duration passed to the subscription event (60s to 30 days)',
  34308: 'Invalid subscribed user list passed to the subscription event',
  34309: 'Invalid page size passed to the subscription event (1 to 200)',
  34312: 'Invalid userProfile parameter',
  34313: 'Invalid userProfileVisibility parameter',
  34314: 'Invalid extra parameter',
  34315: 'Database upgrade failed',
  34316: 'Invalid ChatRoomReceiveMessageConfig parameter',
  34317:
      'The number of chat room message levels exceeds the limit; up to 100 are allowed',
  34318: 'Invalid GroupInfo parameter',
  34319: 'Invalid groupId parameter',
  34320: 'Invalid groupName parameter',
  34321: 'Invalid groupIds parameter',
  34322: 'Invalid GroupMemberRole parameter',
  34323: 'Invalid GroupApplicationStatus parameter',
  34324: 'Invalid GroupApplicationDirection parameter',
  34325: 'Invalid nickname parameter',
  34326: 'Invalid reason parameter',
  34327: 'Invalid remark parameter',
  34328: 'Invalid PagingQueryOption parameter',
  34329: 'Data is being synchronized',
  34330: 'Invalid QueryFriendsDirectionType parameter',
  34331: 'Invalid DirectionType parameter',
  34332: 'Invalid FriendApplicationType parameter',
  34333: 'Invalid FriendApplicationStatus parameter',
  34334: 'Invalid FriendAddPermission parameter',
  34335: 'Invalid extProfile parameter',
  34336: 'Real-time conversation is not enabled',
  34337: 'Client-initiated log upload is not enabled',
  34338: 'The interval for client-initiated log upload exceeds the limit',
  34339: 'The log upload time is duplicated; do not call repeatedly',
  34340: 'Client-initiated log upload failed',
  34341: 'Invalid pushServer parameter',
  34342: 'Invalid statistics endpoint',
  34343: 'Invalid pushToken parameter',
  34344: 'Failed to parse server data',
  35024: 'Invalid message type provided',
  35025: 'Invalid order provided',
  35054:
      'Invalid disableUpdateLastMessage parameter (Ultra Group does not allow true)',
  35055: 'Ultra Group conversations only allow pinning the default channel',
  35056: 'Invalid needReceipt configuration when sending the message',
  35057: 'Voice-to-text is not enabled',
  35058: 'A voice-to-text request is already in progress; do not request again',
  35059:
      'The voice content cannot be converted because the parameter is invalid',
  35060: 'The input parameter type for translation is invalid',
  35061: 'The length of the translation API input list is invalid',
  35062: 'Invalid conversation translation strategy value',
  35063: 'The source language and target language for translation are the same',
  35064: 'The provided translation mode value is invalid',
  35065: 'The specified content to translate is invalid',
  39001: 'Streaming message is unavailable',
  39002:
      'The number of concurrent streaming messages exceeds the limit; up to 3 are allowed',
  39003:
      'The summary expansion key of the streaming message cannot be modified or deleted',
  39004: 'Reset while pulling the streaming message',
  39005: 'Failed to pull the streaming message',
  39006: 'The message content is being pulled; do not request again',
  39007:
      'Streaming message synchronization has completed; no need to pull again',
};
